# Trigger Mode
TriggerMode=Both
# Command Keys
CommandKeys=
# Max Streaming Display Width
MaxStreamingDisplayWidth=60
# Hold Activation Delay (ms)
HoldActivationDelay=300

[TriggerKey]
0=Alt+R

[MenuKey]
0=Control+Shift+Shift_R

[PagePrevKeys]
0=Page_Up
1=KP_Page_Up

[PageNextKeys]
0=Next
1=KP_Next

