github-recovery-codes: ENC[AES256_GCM,data:fOrhKG4V8vz0agjkR3cVyCCWZXWW6eix8V2ilOYxD5b1tYOI33d1rTmmjBYw0wuRjcytBe0mZ4Nrc+/2fj9WIcrlRPtDHuAGa42uw7a3MQWc4pTNZgvVg4m5otK5+mnlKeRAGxHh2owHACVg+BfXnKdSyWFLfVJ8MmixTHP0UKYzOs+pm5OMaN0TotPV/h9Wq1TQkyHe00/rWYq6etwY7ONmP71Bjh/X5NCVLwRteFRhaP50vItFX4SUcnpuc4gF,iv:9gUYjajxQh0YK9/vts7Q/TlFcev+1oC4k4WN7SbyYK8=,tag:d4TqFrq86ZX6FaQDydrFkQ==,type:str]
github_private_key: ENC[AES256_GCM,data:FXvBC2y2PEpu0uhC0LjRCS8BIN8aPf9VU3UiiT7vERWofkkhHQnPFFymrqa/jhhLzobtG2901DWo4WrwJ+lnc6AMIoLz9pJmhnWE+6DjzmDAnVBL4M4hF2nInrO3/hqD04WTif0ay4doA3h3dZ6iwtvqTo4olXFlFCNdWvgHYkhhLfkCjkiagm0Fqq2mki2evMRIxJTA2vh7dj47P0T+dgfK0JP+LUwC6A8yzhZqteCCi7GQCkx5D7gWNKl9kP7DI+im6qGXIckpv7a5D0okD1+l0xPyva5o0siMLgDV9uDiohm5fS0xmaXftUH29K3sQpEzI5ssfLFs0rmeRH1aPuMJ1p9/XS9jIjKhcOoV2ORfcpuN7kkoUu8AR0nQAlKnC1EVPGNhb77kcAHlaOETkrFo8r85YwLJejGgB29W4/pSqObQGPTHyCpb/0X0zBJo8jzFYCuk+iTgRQbklZXRophxX4roHipDnXEO6Uy3AKUtwWWyl9pURLq2RTVMjQZLlHaFpMEAYUzSg1mLn+No82AT6BIUIwh1vSMH4RccNPpVL1Y=,iv:B1X0RyIhlznH42pH404KWciUtOwPd1zsk8ff6pUQZzI=,tag:ug1+usrLiH4A22RV4yLfaQ==,type:str]
bigget_wallent_key: ENC[AES256_GCM,data:2xcbBiWkz47AKdwPJcoGACP6bfDzmQxndLQC93ZlH0hffzEYkkaORKWqwIgyPnCtm2eZIf/zFny91x8SvPqrXsR5CTDeOwWvujXJSQ==,iv:4iJpI0fsw/PA3b3R9wQumlXOIgbEZmXizjHiS38afL4=,tag:2BnQUnhAz8RQudSsnu0uLQ==,type:str]
sops:
    age:
        - recipient: age1xl0yyrfazrsrv6kss0npghrqlt77dx9zma0wjnxjtvmvx6eugp5s2x3ty7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL0Y3ZFBoSmY2K0lvVkxV
            R01SY1pHOHFXcHJ3UXVGSTkyejhBaE9odkNrCnE4Qmx3WktUSTdrZjFNbXpDczV6
            T0R2Q2VVOVJidjdTOWZpYXR4SVl6aFEKLS0tIHI1dDdldWRBK1VPVmVYanhtUWRz
            TXVlakg3NWY4d3l0WGlVS09qTTNZbjgKMR3k1wmYLo50F/avi+NATaJNHbvprpJZ
            UbJ08i74ECqpI8YMrbQQQ3IPiQ/ANGwCrsvzMEQCgAXEVs1PUVY1hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T04:16:33Z"
    mac: ENC[AES256_GCM,data:G4OU4qOqinHE0TsDN34py/s7SkA9I0hI7UQv3C7r07F+hxHISVG4lgIWp5NbscbRpRJ1OQ1Obij5Hb//xxc+qj5o+IQS0du0qu/A6utSGOijUA3P0hy1ae84evhQbFQ7OmWfBq+xi2TOGWsL6+56quUpvgmtYu4FIy3AJ02wgEY=,iv:LJ66/e1f+QUYdw87+eRGyd3xmqneRJYPgQ0uEVOt47Q=,tag:Y8nWUZDZhzVCW0saEFm6NQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
